### ISSUE TITLE
I don't understand the operation to install it

### ISSUE THREAD

**Issue by Jean63** [hectorjsmith/fail2ban-prometheus-exporter#1]
Hi @hectorjsmith,

Thank you for you work.
I download the binary file, and i launch it on my client prometheus with fail2ban.
I import the .json file on my graphana server but i have an empty dashboard ..

![Screenshot_20230420_144915](https://user-images.githubusercontent.com/16014301/233371058-5e459de8-3967-48ea-b25d-d76ee213ee2a.png)

**Comment by ahdzesq** [comment]
did you have configured the job into your Prometheus?

**Comment by ehnwebmaster** [comment]
> /etc/prometheus/prometheus.yml

Something like that;

```
# fail2ban_exporter


  - job_name: fail2ban
    metrics_path: /metrics
    static_configs:
      - targets: ['localhost:9191']
```
