### ISSUE TITLE
Add wget in docker image for healthcheck

### ISSUE THREAD

**Issue by llaumgui** [hectorjsmith/fail2ban-prometheus-exporter#3]
Hi,

presently, there isn't any curl or wget binary. It's not possible to do a healthcheck like that :

```
healthcheck:
  test: ["CMD-SHELL", "wget --no-verbose --tries=1 http://localhost:9191/ -q -O /dev/null || exit 1"]
  interval: 1m
  timeout: 10s
  start_period: 30s
```

And if you add wget, why not add healthcheck directly on DockerFile ?
